Repository swiftwasm/JavaScriptKit, pull requests merged in 2020-10, with the labels that each got.

#86 Make `JSError` conform to `JSBridgedClass`
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSError.swift
Labels: bug

#88 Rename JSValueConvertible/Constructible/Codable
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSPromise.swift
  Sources/JavaScriptKit/BasicObjects/JSTypedArray.swift
  Sources/JavaScriptKit/ConstructibleFromJSValue.swift
  Sources/JavaScriptKit/ConvertibleToJSValue.swift
  Sources/JavaScriptKit/Deprecated.swift
  Sources/JavaScriptKit/FundamentalObjects/JSFunction.swift
  Sources/JavaScriptKit/FundamentalObjects/JSObject.swift
  Sources/JavaScriptKit/JSBridgedType.swift
  Sources/JavaScriptKit/JSValue.swift
  Sources/JavaScriptKit/JSValueDecoder.swift
Labels: enhancement

#99 Bump version to 0.8.0, update `CHANGELOG.md`
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#101 Mention `carton` Docker image and refine wording in `README.md`
  README.md
Labels: documentation

#105 Fix branch and triple in `compatibility.yml`
  .github/workflows/compatibility.yml
Labels: bug
