Repository swiftwasm/JavaScriptKit, pull requests merged in 2020-09, with the labels that each got.

#47 Add JSError with tests, add JSObject.description
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSError.swift
  Sources/JavaScriptKit/FundamentalObjects/JSObject.swift
Labels: enhancement

#45 Add JSDate implementation with tests
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSDate.swift
Labels: enhancement

#46 Add JSTimer implementation with tests
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSTimer.swift
Labels: enhancement

#49 Generate and publish documentation with `swift-doc`
  .github/workflows/documentation.yml
  Sources/JavaScriptKit/BasicObjects/JSError.swift
  Sources/JavaScriptKit/FundamentalObjects/JSFunction.swift
Labels: documentation

#65 Update Node.js dependencies
  Example/package-lock.json
  Example/package.json
  IntegrationTests/package-lock.json
  IntegrationTests/package.json
  Runtime/package-lock.json
  Runtime/package.json
Labels: dependencies

#62 Add a generic `JSPromise` implementation
  IntegrationTests/TestSuites/Sources/PrimaryTests/main.swift
  Sources/JavaScriptKit/BasicObjects/JSArray.swift
  Sources/JavaScriptKit/BasicObjects/JSError.swift
  Sources/JavaScriptKit/BasicObjects/JSPromise.swift
  Sources/JavaScriptKit/BasicObjects/JSTypedArray.swift
Labels: enhancement

#71 Create `CHANGELOG.md`
  CHANGELOG.md
Labels: documentation

#76 Release version 0.7.0
  CHANGELOG.md
  Runtime/src/index.ts
  Sources/JavaScriptKit/Compatibility.swift
  package-lock.json
  package.json
Labels: documentation

#78 Specify correct SwiftWasm snapshot in `README.md`
  README.md
Labels: documentation

#81 Fix runtime files location in `package.json`
  package.json
Labels: bug

#85 Add missing .npmignore, bump version to 0.7.2
  CHANGELOG.md
  Runtime/.npmignore
  package-lock.json
  package.json
Labels: bug
